// constants/products.ts

export type Product = {
  id?: number;
  name?: string;
  price?: number;
  originalPrice?: number;
  image?: string;
  category?: string;
  rating?: number;
  reviews?: number;
  discount?: number;
  brand?: string;
  description?: string;
  features?: string[];
  specifications?: {
    [key: string]: string;
  };
  colors?: string[];
  sizes?: string[];
  inStock?: boolean;
  stockCount?: number;
};

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 99.99,
    originalPrice: 129.99,
    image:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop",
    category: "Electronics",
    rating: 4.5,
    reviews: 128,
    discount: 23,
    brand: "TechSound",
    description:
      "Premium wireless headphones with active noise cancellation, 30-hour battery life, and superior sound quality. Perfect for music lovers and professionals.",
    features: [
      "Active Noise Cancellation",
      "30-hour battery life",
      "Quick charge - 5 min = 3 hours",
      "Bluetooth 5.0 connectivity",
      "Premium leather ear cups",
      "Foldable design",
    ],
    specifications: {
      "Driver Size": "40mm",
      "Frequency Response": "20Hz - 20kHz",
      Impedance: "32 ohms",
      Battery: "30 hours",
      Charging: "USB-C",
      Weight: "250g",
    },
    colors: ["Black", "White", "Silver", "Blue"],
    sizes: ["Small", "Medium", "Large"],
    inStock: true,
    stockCount: 15,
  },
  {
    id: 2,
    name: "Smart Watch",
    price: 199.99,
    originalPrice: 249.99,
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&h=300&fit=crop",
    category: "Electronics",
    rating: 4.7,
    reviews: 89,
    discount: 20,
    brand: "SmartTech",
    description:
      "Advanced fitness tracking smartwatch with heart rate monitoring, GPS, and 7-day battery life. Stay connected and healthy with comprehensive health tracking.",
    features: [
      "Heart Rate Monitoring",
      "GPS Tracking",
      "7-day battery life",
      "Water resistant up to 50m",
      "Sleep tracking",
      "Multiple sport modes",
      "Smart notifications",
    ],
    specifications: {
      Display: "1.4 inch AMOLED",
      Battery: "7 days",
      "Water Rating": "5ATM (50m)",
      Connectivity: "Bluetooth 5.0, WiFi",
      Sensors: "HR, GPS, Accelerometer, Gyroscope",
      Weight: "45g",
      Compatibility: "iOS & Android",
    },
    colors: ["Black", "Silver", "Rose Gold"],
    sizes: ["Small", "Medium", "Large"],
    inStock: true,
    stockCount: 8,
  },
  {
    id: 3,
    name: "Running Shoes",
    price: 79.99,
    originalPrice: 99.99,
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=300&fit=crop",
    category: "Fashion",
    rating: 4.3,
    reviews: 156,
    discount: 20,
    brand: "SportMax",
    description:
      "Lightweight running shoes with responsive cushioning and breathable mesh upper. Perfect for daily runs, workouts, and athletic activities.",
    features: [
      "Responsive EVA cushioning",
      "Breathable mesh upper",
      "Lightweight design",
      "Durable rubber outsole",
      "Comfortable padded collar",
      "Reflective details for visibility",
    ],
    specifications: {
      Weight: "280g (size 9)",
      Drop: "10mm",
      "Upper Material": "Engineered mesh",
      Sole: "Rubber with traction pattern",
      Cushioning: "EVA foam midsole",
      Type: "Road running",
      "Arch Support": "Medium",
    },
    colors: ["Black", "White", "Blue", "Red"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    inStock: true,
    stockCount: 25,
  },
  {
    id: 4,
    name: "Coffee Maker",
    price: 149.99,
    originalPrice: 199.99,
    image:
      "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=300&h=300&fit=crop",
    category: "Home",
    rating: 4.6,
    reviews: 73,
    discount: 25,
    brand: "BrewMaster",
    description:
      "Professional-grade coffee maker with programmable settings and thermal carafe. Brew the perfect cup every time with precision temperature control.",
    features: [
      "24-hour programmable timer",
      "Thermal stainless steel carafe",
      "Auto shut-off safety feature",
      "Built-in water filtration",
      "Brew strength selector",
      "Easy-clean design",
      "Anti-drip system",
    ],
    specifications: {
      Capacity: "12 cups (60 oz)",
      Power: "1000W",
      Carafe: "Double-wall thermal stainless steel",
      Timer: "24-hour programmable",
      Dimensions: "14 x 10 x 16 inches",
      Weight: "8 lbs",
      "Water Reservoir": "Removable",
    },
    colors: ["Black", "Stainless Steel"],
    sizes: ["Standard"],
    inStock: true,
    stockCount: 12,
  },
  {
    id: 5,
    name: "Laptop Backpack",
    price: 49.99,
    originalPrice: 69.99,
    image:
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300&h=300&fit=crop",
    category: "Fashion",
    rating: 4.4,
    reviews: 94,
    discount: 29,
    brand: "TechCarry",
    description:
      "Professional laptop backpack with multiple compartments and USB charging port. Perfect for work, travel, and daily commuting with anti-theft features.",
    features: [
      "Fits laptops up to 15.6 inches",
      "USB charging port",
      "Anti-theft hidden zipper",
      "Water-resistant material",
      "Multiple organized compartments",
      "Comfortable padded straps",
      "Business card holder",
    ],
    specifications: {
      "Laptop Compartment": "15.6 inch max",
      Material: "Oxford fabric with PVC coating",
      Dimensions: "18 x 12 x 6 inches",
      Weight: "2.2 lbs",
      Capacity: "35L",
      Features: "USB port, anti-theft",
      Warranty: "1 year",
    },
    colors: ["Black", "Grey", "Navy Blue"],
    sizes: ["Standard"],
    inStock: true,
    stockCount: 18,
  },
  {
    id: 6,
    name: "Bluetooth Speaker",
    price: 59.99,
    originalPrice: 79.99,
    image:
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=300&h=300&fit=crop",
    category: "Electronics",
    rating: 4.2,
    reviews: 67,
    discount: 25,
    brand: "SoundWave",
    description:
      "Portable Bluetooth speaker with 360-degree surround sound and 12-hour battery life. Waterproof design perfect for outdoor adventures and parties.",
    features: [
      "360-degree surround sound",
      "12-hour battery life",
      "IPX7 waterproof rating",
      "Bluetooth 5.0 connectivity",
      "Built-in microphone",
      "Compact portable design",
      "Bass boost technology",
    ],
    specifications: {
      "Power Output": "20W",
      Battery: "2400mAh (12 hours)",
      Bluetooth: "5.0 (33ft range)",
      "Water Rating": "IPX7",
      Dimensions: "7 x 3 x 3 inches",
      Weight: "1.2 lbs",
      Charging: "USB-C",
    },
    colors: ["Black", "Blue", "Red", "White"],
    sizes: ["Standard"],
    inStock: true,
    stockCount: 22,
  },
  {
    id: 7,
    name: "Smartphone Case",
    price: 19.99,
    originalPrice: 29.99,
    image:
      "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=300&h=300&fit=crop",
    category: "Electronics",
    rating: 4.1,
    reviews: 203,
    discount: 33,
    brand: "GuardTech",
    description:
      "Heavy-duty smartphone case with military-grade protection and wireless charging compatibility. Drop-tested and scratch-resistant design.",
    features: [
      "Military-grade drop protection",
      "Wireless charging compatible",
      "Scratch-resistant surface",
      "Precise port cutouts",
      "Raised camera protection",
      "Easy grip texture",
      "Screen protector included",
    ],
    specifications: {
      Protection: "Military Standard 810G",
      "Drop Height": "6.6 feet tested",
      Material: "TPU + PC hybrid",
      Compatibility: "iPhone 14/13/12 series",
      Features: "Wireless charging, magnetic",
      "Colors Available": "Multiple options",
      Warranty: "Lifetime replacement",
    },
    colors: ["Clear", "Black", "Blue", "Pink", "Green"],
    sizes: ["iPhone 12", "iPhone 13", "iPhone 14", "iPhone 15"],
    inStock: true,
    stockCount: 45,
  },
  {
    id: 8,
    name: "Winter Jacket",
    price: 89.99,
    originalPrice: 120.0,
    image:
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=300&h=300&fit=crop",
    category: "Fashion",
    rating: 4.6,
    reviews: 87,
    discount: 25,
    brand: "WarmGuard",
    description:
      "Premium winter jacket with down insulation and weather-resistant shell. Designed for extreme cold conditions with adjustable hood and multiple pockets.",
    features: [
      "90% down insulation",
      "Weather-resistant shell",
      "Adjustable hood with fur trim",
      "Multiple zippered pockets",
      "Wind-resistant cuffs",
      "Breathable inner lining",
      "Machine washable",
    ],
    specifications: {
      Insulation: "90% down, 10% feathers",
      Shell: "Polyester with DWR coating",
      "Temperature Rating": "-20°F to 40°F",
      "Water Resistance": "10,000mm",
      Weight: "2.1 lbs",
      Pockets: "6 (4 external, 2 internal)",
      Care: "Machine washable",
    },
    colors: ["Black", "Navy", "Forest Green", "Burgundy"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    stockCount: 14,
  },
  {
    id: 9,
    name: "Gaming Mouse",
    price: 69.99,
    originalPrice: 89.99,
    image:
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=300&h=300&fit=crop",
    category: "Electronics",
    rating: 4.7,
    reviews: 156,
    discount: 22,
    brand: "GamePro",
    description:
      "High-precision gaming mouse with customizable RGB lighting and programmable buttons. Ergonomic design for extended gaming sessions with adjustable DPI.",
    features: [
      "12,000 DPI precision sensor",
      "Customizable RGB lighting",
      "8 programmable buttons",
      "Ergonomic right-hand design",
      "Braided cable with gold-plated USB",
      "On-the-fly DPI switching",
      "Gaming software included",
    ],
    specifications: {
      Sensor: "Optical 12,000 DPI",
      Buttons: "8 programmable",
      "Polling Rate": "1000 Hz",
      Cable: "6ft braided USB",
      Lighting: "16.7M color RGB",
      Weight: "85g",
      Compatibility: "Windows, Mac, Linux",
    },
    colors: ["Black", "White", "RGB"],
    sizes: ["Standard"],
    inStock: true,
    stockCount: 31,
  },
  {
    id: 10,
    name: "Water Bottle",
    price: 24.99,
    originalPrice: 34.99,
    image:
      "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=300&h=300&fit=crop",
    category: "Sports",
    rating: 4.4,
    reviews: 91,
    discount: 29,
    brand: "HydraMax",
    description:
      "Insulated stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12 hours. BPA-free with leak-proof design and wide mouth opening.",
    features: [
      "Double-wall vacuum insulation",
      "24h cold / 12h hot retention",
      "BPA-free stainless steel",
      "Leak-proof cap design",
      "Wide mouth for easy filling",
      "Sweat-proof exterior",
      "Dishwasher safe",
    ],
    specifications: {
      Capacity: "32 oz (946ml)",
      Material: "18/8 stainless steel",
      Insulation: "Double-wall vacuum",
      Dimensions: "10.5 x 3.5 inches",
      Weight: "1.1 lbs",
      Opening: "2.16 inch wide mouth",
      Care: "Top-rack dishwasher safe",
    },
    colors: ["Black", "White", "Blue", "Pink", "Green", "Stainless"],
    sizes: ["20oz", "32oz", "40oz"],
    inStock: true,
    stockCount: 27,
  },
  {
    id: 11,
    name: "Sunglasses",
    price: 89.99,
    originalPrice: 119.99,
    image:
      "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=300&h=300&fit=crop",
    category: "Fashion",
    rating: 4.5,
    reviews: 76,
    discount: 25,
    brand: "SunShield",
    description:
      "Premium polarized sunglasses with UV400 protection and lightweight titanium frame. Classic aviator design suitable for all face shapes and outdoor activities.",
    features: [
      "100% UV400 protection",
      "Polarized lenses",
      "Lightweight titanium frame",
      "Anti-reflective coating",
      "Scratch-resistant lenses",
      "Comfortable nose pads",
      "Premium carrying case included",
    ],
    specifications: {
      "UV Protection": "100% UV400",
      Lens: "TAC polarized",
      Frame: "Titanium alloy",
      Weight: "25g",
      "Lens Width": "58mm",
      Bridge: "18mm",
      Temple: "140mm",
    },
    colors: ["Black", "Gold", "Silver", "Brown"],
    sizes: ["Standard"],
    inStock: true,
    stockCount: 19,
  },
  {
    id: 12,
    name: "Wireless Charger",
    price: 44.99,
    originalPrice: 59.99,
    image:
      "https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?w=300&h=300&fit=crop",
    category: "Electronics",
    rating: 4.6,
    reviews: 134,
    discount: 25,
    brand: "ChargeTech",
    description:
      "Fast wireless charging pad with Qi-certification and LED indicator. Compatible with all Qi-enabled devices including iPhone and Samsung Galaxy series.",
    features: [
      "Qi-certified fast charging",
      "15W max charging speed",
      "LED charging indicators",
      "Foreign object detection",
      "Over-temperature protection",
      "Non-slip charging surface",
      "Case-friendly up to 5mm",
    ],
    specifications: {
      Output: "15W/10W/7.5W/5W",
      Input: "9V/2A, 5V/3A",
      Efficiency: ">75%",
      "Charging Distance": "≤8mm",
      Dimensions: "4.1 x 4.1 x 0.4 inches",
      Weight: "5.6 oz",
      Cable: "3.3ft USB-C included",
    },
    colors: ["Black", "White"],
    sizes: ["Standard"],
    inStock: true,
    stockCount: 33,
  },
];
